# Configure Spring Boot default port : Heroku $PORT or 8080
server:
  port: ${PORT:8080}

# Database connection
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      connection-test-query: SELECT 1

  sql:
    init:
      platform: h2

  jpa:
    database: H2
    show-sql: true
    generate-ddl: true
    hibernate:
      # validate – Hibernate only validates whether the tables and columns exist; otherwise, it throws an exception.
      # https://www.baeldung.com/spring-boot-data-sql-and-schema-sql
      ddl-auto: validate

  # https://reflectoring.io/database-migration-spring-boot-flyway/
  flyway:
    # This will create the migration History table by which we will ensure that SQL script is executed or not
    baseline-on-migrate: true
    # For validating script
    validate-on-migrate: true
    # SQL script locations
    locations: classpath:db/migration

    # Flyway file name syntax
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql